// <auto-generated />
using GreenThumbGLevel.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumbGLevel.Migrations
{
    [DbContext(typeof(GreenThumbDbContext))]
    [Migration("20231207114914_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GreenThumbGLevel.Models.Instruction", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantName");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            Description = "undvik direkt solljus",
                            PlantName = "Fiolfikus"
                        },
                        new
                        {
                            InstructionId = 2,
                            Description = "Låt den torka lätt mellan vattningarna för att undvika rotröta.",
                            PlantName = "Fiolfikus"
                        },
                        new
                        {
                            InstructionId = 3,
                            Description = "Duscha den gärna regelbundet på bladen för att bibehålla hög luftfuktighet",
                            PlantName = "Fiolfikus"
                        },
                        new
                        {
                            InstructionId = 4,
                            Description = "Guldpalmen trivs i omgivningar utan direkt solljus.",
                            PlantName = "Guldpalm"
                        },
                        new
                        {
                            InstructionId = 5,
                            Description = "Under vinterhalvåret behöver den mindre näring.",
                            PlantName = "Guldpalm"
                        },
                        new
                        {
                            InstructionId = 6,
                            Description = "Sätt gärna ut på den på balkongen eller terrassen om sommaren i skuggan.",
                            PlantName = "Guldpalm"
                        },
                        new
                        {
                            InstructionId = 7,
                            Description = "Papegojblomma trivs i miljöer med god tillgång till ljus",
                            PlantName = "Vit Papegojblomma"
                        },
                        new
                        {
                            InstructionId = 8,
                            Description = "Undvik direkt solljus som kan bränna bladen.",
                            PlantName = "Vit Papegojblomma"
                        },
                        new
                        {
                            InstructionId = 9,
                            Description = "Låt den torka lätt mellan vattningarna, men duscha den gärna ofta på bladen för att bibehålla hög luftfuktighet. ",
                            PlantName = "Vit Papegojblomma"
                        });
                });

            modelBuilder.Entity("GreenThumbGLevel.Models.Plant", b =>
                {
                    b.Property<string>("PlantName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantName");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantName = "Vit Papegojblomma",
                            PlantDescription = "Stor och vacker planta med stora gröna blad som växer i solfjäderform.",
                            PlantOrigin = "Danmark"
                        },
                        new
                        {
                            PlantName = "Monstera",
                            PlantDescription = "Mycket lättskött och populär planta med stora, blanka, gröna blad och långa luftrötter.",
                            PlantOrigin = "Nederländerna"
                        },
                        new
                        {
                            PlantName = "Guldpalm",
                            PlantDescription = "Frodig, lättskött och populär palm med vackra blad som ger inredningen en tropisk touch.",
                            PlantOrigin = "Danmark"
                        },
                        new
                        {
                            PlantName = "Fiolfikus",
                            PlantDescription = "Trendig växt med fiolformade, glänsande, stora blad. En populär och lättskött planta som trivs i ljusa förhållanden, undvik direkt solljus.",
                            PlantOrigin = "Danmark"
                        });
                });

            modelBuilder.Entity("GreenThumbGLevel.Models.Instruction", b =>
                {
                    b.HasOne("GreenThumbGLevel.Models.Plant", "Plant")
                        .WithMany("Instruction")
                        .HasForeignKey("PlantName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumbGLevel.Models.Plant", b =>
                {
                    b.Navigation("Instruction");
                });
#pragma warning restore 612, 618
        }
    }
}
